### ISSUE TITLE
A issue about dataset of VQA2 on preprocessing. 

### ISSUE THREAD

**Issue by Winyi** [yuzcccc/vqa-mfb#10]
@yuzcccc Hi, Yu. When I do the preprocess for extracting features, I use the  workstation with 2 TITAN. But the code use the GPU memory only 4G, the remaining 20G is not used, the code running speed is very slow. Could you tell me how to make full use of the 2 TITAN, and improve the code running speed?

**Comment by yuzcccc** [comment]
We have updated this repo and migrate our MFB/MFH models to our new project [openvqa](https://github.com/MILVLG/openvqa) based on PyTorch, which includes high-speed data loader, as well as the pre-trained models based on Faster RCNN visual features
