### ISSUE TITLE
error on building caffe

### ISSUE THREAD

**Issue by ydzhang12345** [yuzcccc/vqa-mfb#2]
[ RUN      ] LayerFactoryTest/1.TestCreateLayer
src/caffe/test/test_layer_factory.cpp:47: Failure
Value of: layer->type()
  Actual: "MatMul2"
Expected: iter->first
Which is: "MatMul"
[  FAILED  ] LayerFactoryTest/1.TestCreateLayer, where TypeParam = caffe::CPUDevice<double> (195 ms)

Any advice? I guess the error is due to the custom layer.

**Comment by yuzcccc** [comment]
I think this error happens when you run the test script and caffe is correctly build, You can ignore this or just remove the corresponding layers (the cpp, cu & hpp), as this layer is not used in the mfb project (only for my personal use in other project).
