### ISSUE TITLE
FRCN Image features generation

### ISSUE THREAD

**Issue by ahmedmagdiosman** [yuzcccc/vqa-mfb#3]
Hi!
How did you generate the FRCN image features? Would you be willing to share that code?

**Comment by yuzcccc** [comment]
I just use the codes (tools/generate_tsv.py)  in the 'bottom-up-attention' project, Rather than storing the feature with a huge .tsv file, I modified a couple of lines in the `generate_tsv` function to save each feature as a .npz file. I think this is very simple if you look at their scripts.

**Comment by ahmedmagdiosman** [comment]
Thanks a lot!
