### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by NightlyJourney** [yuzcccc/vqa-mfb#4]
Hi Yu, when I am trying to run the code, I noticed that the config.py in mfh_coatt_glove contains some data files such as 'OpenEnded_mscoco_train2014_questions.json', but I have not found these files in the link you provided (http://visualqa.org/download.html). Could you please tell me where can I find those files? Thanks a lot.

**Comment by yuzcccc** [comment]
'OpenEnded_mscoco_train2014_questions.json' corresponds to the VQA-1.0 dataset(http://visualqa.org/vqa_v1_download.html). If you run the VQA-2.0 dataset, you should modify it to 'v2_OpenEnded_mscoco_train2014_questions.json'

**Comment by NightlyJourney** [comment]
Hi Yu, thank you so much for your timely reply (and sorry for my late response...). The VQA dataset problem seems resolved with your kind advice, but some new problems concerning dataset arose. I would truly appreciated if you could give me some suggestions on them:

1. About genome dataset, the link you provided (https://visualgenome.org/api/v0/api_home.html) offers 3 different versions of genome dataset, which one should I pick? Besides, I have downloaded question answers files of both ver1.0 and ver1.2, but neither of them named 'OpenEnded_genome_train_questions.json' , which is the file name you set in config.py.

2. I have downloaded genome images and image meta, and put them in the data path of 'genome' in config.py. As I see, the 'genome features_prefix' in config.py is the path for Genome images, but it doesn't work. The whole error is as follows:
'''
restoring vocab
question vocab size: 13321
answer vocab size: 3000
parsed 248349 questions for train
data not found for qid :  451834 train
Traceback (most recent call last):
  File "train_mfh_coatt_glove.py", line 194, in <module>
    train()
  File "train_mfh_coatt_glove.py", line 103, in train
    for iter_idx, (data, word_length, feature, answer, glove, epoch) in enumerate(train_Loader):
  File "/home/***/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 201, in __next__
    return self._process_next_batch(batch)
  File "/home/***/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 221, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/***/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/***/***/github/vqa-mfb.pytorch/mfh_coatt_glove/utils/data_provider.py", line 338, in __getitem__
    word, cont, feature, answer, glove_matrix, _, _, epoch = self.dp.get_batch_vec()
  File "/home/***/***/github/vqa-mfb.pytorch/mfh_coatt_glove/utils/data_provider.py", line 320, in get_batch_vec
    t_batch = self.create_batch(t_qid_list)
  File "/home/***/***/github/vqa-mfb.pytorch/mfh_coatt_glove/utils/data_provider.py", line 268, in create_batch
    ivec[i,:,0:t_ivec.shape[1]] = t_ivec
AttributeError: 'float' object has no attribute 'shape'

*** Error in `python': corrupted size vs. prev_size: 0x000000000134ac80 ***
Aborted (core dumped)
'''

BTW, may I know the configuration of your server that run the code? It looks that our server is out of memeory in the process. Thanks a lot.

**Comment by yuzcccc** [comment]
Hi, 
1. the genome question is generated by myself to make it fit the format of the VQA datasets. The preprocess scripts I use is here (https://github.com/akirafukui/vqa-mcb/blob/master/preprocess/vg_preprocessing.py). The version is not that important as the QA part in visual genome is not updated. 

2. I don't load the raw genome images. Instead, I extract the bottom-up features and the genome features_prefix correspond to the feature path. For each image, a npz file with extracted features is used, just like the procedures for the coco images. Read the Prerequisites carefully

3. I use a workstation with 64GB memory and GTX 1080. To run the code, the GPU memory should at least 6GB.

**Comment by NightlyJourney** [comment]
Got it, I just missed the data preprocessing part of your model, thank you so much :)

**Comment by NightlyJourney** [comment]
Hi Yu, I have not found any code in 'extract_resnet.py' that preprocess the Genome images, so do I need to add the code manually or there is another .py file handle the Genome images preprocess? Thanks a lot.

**Comment by yuzcccc** [comment]
To extract features for Visual Genome, I just modified a few lines of the 'extract_resnet.py'  since their procedure are exactly the same

**Comment by NightlyJourney** [comment]
Roger that. Thanks for your help :)
