### ISSUE TITLE
pretrained model of MFH+RCN?

### ISSUE THREAD

**Issue by ydzhang12345** [yuzcccc/vqa-mfb#5]
Thank you for your work !

Can you release the pretrained model of MFH+RCN as well?

**Comment by Hediby** [comment]
I would also be interested. Thanks !

**Comment by yuzcccc** [comment]
We have updated this repo and migrate our MFB/MFH models to our new project [openvqa](https://github.com/MILVLG/openvqa) based on PyTorch, which includes high-speed data loader, as well as the pre-trained models based on Faster RCNN visual features
