### ISSUE TITLE
Cannot re-implement result of MFH (FRCN img features) on COCO-VQA v2.0

### ISSUE THREAD

**Issue by cengzy14** [yuzcccc/vqa-mfb#9]
The result reported is 68.76%. I use the features from Bottom-Up Attention[https://github.com/peteanderson80/bottom-up-attention](url), and use the same architecture as yours MFH, but only get 68.58% in the test-dev set. Is there anything different from the original MFH+CoAtt+GloVe? What should I pay attention to when re-implement? Thank you very much! Your code is very helpful!

**Comment by yuzcccc** [comment]
try to use the snapshot at the 90k (or 85k) iterations if you use the train+val as the trainset. Too few or too many iterations may lead to inferior performance.
